
server:
  port: 8765
spring:
  application:
    name: wagu-gateway
  cloud:
    config:
      discovery:
        enabled: true
        service-id: wagu-config
  profiles:
    active: dev

zuul:
  ribbon-isolation-strategy: thread
  routes:
    wagu-post: /api/post/**
    wagu-user: /api/account/**
    wagu-comment: /api/comment/**
    wagu-search: /api/search/**
  strip-prefix: true

management:
  endpoint:
    routes:
      enabled: true
